ДЗ 1
Slava-Romanov/kts-front-summer-2021 pull request #1
Opened 2021-08-28 14:50 UTC by Slava-Romanov

2021-08-30 20:11 UTC, kirBMSTU requested changes
Заметил, что часть с версткой сделали сразу на реакте. Это круто!
Однако есть несколько замечаний, которые важно поправить.
- весь код писать на TS. Сейчас же первая часть ДЗ сделана на js
- избавиться от каскадов (вложенных селекторов в стилях), и селекторов по тегу (пользоваться классами)
- избавиться от древовидной структуры и чрезмерного дробления стилей и посмотреть в сторону css-модулей
- добавить линтер

2021-08-30 20:11 UTC, kirill-gadzhiev commented on src/index.tsx
> +import React from 'react';
рекомендую настроить линтер. В файлах разные кавычки, импорты в случайном порядке, а линтер могу бы поправить это автоматически)

2021-08-30 20:11 UTC, kirill-gadzhiev commented on src/layouts/git-repo-tile/__additional-info/git-repo-tile__additional-info.css
> +.git-repo-tile__additional-info span + span {
не очень хорошо использовать такие сложные селекторы, при изменении в верстке можно запросто что-то упустить. Лучше навесить нужный класс-модификатор

2021-08-30 20:11 UTC, kirill-gadzhiev commented on src/layouts/git-repo-tile/__additional-info/git-repo-tile__additional-info.css
> +.git-repo-tile__additional-info span + span {
Ну и лучше использовать именно селекторы по классу, а не по тегу

2021-08-30 20:11 UTC, kirill-gadzhiev commented on src/layouts/git-repo-tile/__avatar/git-repo-tile__avatar.css
> +.git-repo-tile__avatar {
странные названия директорий. Насколько я понимаю это заимствовано из бэма, однако сейчас такое не особо принято. Советую поправить. Самый частый вариант - именование директории по названию компонента, например GitRepoTile. Внутри бы лежали index.ts, GitRepoTile.tsx и GitRepoTitle.css а также папки со специфичными компонентами потомками (в папках с аналогичными именованием и структурой)

2021-08-30 20:11 UTC, kirill-gadzhiev commented on src/layouts/git-repo-tile/__content/git-repo-tile__content.css
> +.git-repo-tile__content > *:last-child {
аналогично лучше завязываться именно на классы и не усложнять

2021-08-30 20:11 UTC, kirill-gadzhiev commented on src/layouts/git-repo-tile/git-repo-title.js
> +        </div>
в целом можно сразу стилизовать img, дополнительная обертка необязательна

2021-08-30 20:11 UTC, kirill-gadzhiev commented on src/layouts/git-repo-tile/git-repo-title.js
> +            </div>
аналогично здесь можно было навесить стили сразу на тег **a**

2021-08-30 20:11 UTC, kirill-gadzhiev commented on src/layouts/git-repo-tile/git-repo-title.js
> +import './__content/git-repo-tile__content.css'
лучше либо написать все стили в одном файле (кажется их тут не сильно много), либо разбить на отдельные компоненты со своими версткой и стилями

2021-08-30 20:11 UTC, kirill-gadzhiev commented on src/layouts/git-repo-tile/git-repo-title.js
> +import './__content/git-repo-tile__content.css'
Также советую ознакомиться с css-модулями

2021-08-30 20:11 UTC, kirill-gadzhiev commented on src/layouts/input/input.js
> +    return <input placeholder='Введите название организации' className='input' disabled={disabled ? true:''}/>;
Опять же, этим по=хорошему должен заниматься линтер, однако если его нет, то лучше вручную разбивать такие длинные строки

2021-08-30 20:11 UTC, kirill-gadzhiev commented on src/layouts/repos-list/repos-list.css
> +    width: 397px;
лучше не хардкодить ширину, верстка должна быть адаптивной и зависеть от родителя и соседей / ширины экрана

2021-08-30 20:11 UTC, kirill-gadzhiev commented on src/layouts/repos-list/repos-list.js
> +            <GitRepoTitle avatar={avatarImg2} title="very-long-repository-name-and-long" orgLink="ktsstudio" raiting="123" date="Updated 21 Jul"/>
можно было отдельно задать в массиве пропсы, а тут проитерироваться и всего один раз написать компонент GitRepoTitle

2021-08-30 20:11 UTC, kirill-gadzhiev commented on src/layouts/search-button/search-button.css
> +.search-button:enabled {
достаточно задавать disabled

2021-08-30 20:11 UTC, kirill-gadzhiev commented on src/layouts/search-button/search-button.js
> +    return <button className='search-button' disabled={disabled ? true:''}>
лучше все же оборачивать верстку в скобки, чтобы открывающий и закрывающие теги находились друг под другом, так проще читать код

2021-08-30 20:11 UTC, kirill-gadzhiev commented on src/layouts/search-button/search-button.js
> +import findIcon from './../img/findIcon.svg'
картинку можно положить в этой папке

2021-08-30 20:11 UTC, kirill-gadzhiev commented on src/shared/store/ApiStore/ApiStore.ts
> +                'Content-Type': 'text/plain;charset=UTF-8'
точно ли такой Content-Type?)

2021-08-30 20:11 UTC, kirill-gadzhiev commented on src/shared/store/ApiStore/ApiStore.ts
> +            endPoint = `${(endPoint)}?${qs.stringify(params.data)}`;
получается знак вопроса добавляется в урл в любом случае, даже если параметры не переданы

2021-08-30 20:11 UTC, kirBMSTU commented on src/shared/store/ApiStore/ApiStore.ts
> +                status: response.status
можно было не писать if, а просто прокинуть response.ok в поле success

2021-08-30 20:11 UTC, kirBMSTU commented on .gitignore
> +public/
кажется из-за того что public в .gitignore, не могу запустить проект у себя (в гите просто нет файла index.html

2021-09-04 16:25 UTC, Slava-Romanov commented on src/index.tsx
> +import React from 'react';
ЛИнтер добавлен

2021-09-04 16:25 UTC, Slava-Romanov commented on src/layouts/git-repo-tile/__additional-info/git-repo-tile__additional-info.css
> +.git-repo-tile__additional-info span + span {
Добавлено

2021-09-26 13:57 UTC, merged