ДЗ2
Slava-Romanov/kts-front-summer-2021 pull request #2
Opened 2021-09-04 20:41 UTC by Slava-Romanov

ДЗ2 + Доп задание

2021-09-11 19:19 UTC, natalya-z commented on src/components/RepoTile/RepoTile.tsx
> +    RepoItem,
Переменные пишутся с маленькой буквы. Сейчас получается, что одинаково называется и переменная и ее тип - это неправильно

2021-09-11 19:19 UTC, natalya-z commented on src/components/RepoTile/RepoTile.tsx
> +                    letter={RepoItem.owner.login.slice(1)}
Можно было сделать деструктуризацию RepoItem

2021-09-11 19:23 UTC, natalya-z commented on src/components/RepoTile/RepoTile.tsx
> +    const dateFormat = (date: string) => {
Данную функцию необходимо вынести вне компонента, так как она не изменяет внутренние переменные компонента

2021-09-11 19:23 UTC, natalya-z commented on src/components/ReposListContainer/ReposListContainer.tsx
> +export default ReposListContainer;
Нужно мемоизировать компонент

2021-09-11 19:45 UTC, natalya-z commented on src/pages/RepoSearchPage/RepoSearchPage.tsx
> +                        onClick={() => onClickRepo(repo)}
Можно было сделать функцию `const onClickRepo = (repo: RepoItem): void => (): void =>` и добавить сюда `onClick={onClickRepo(repo)}`

2021-09-11 19:46 UTC, natalya-z commented on src/pages/RepoSearchPage/RepoSearchPage.tsx
> +const RepoSearchPage = (): JSX.Element => {
React.FC

2021-09-11 19:51 UTC, natalya-z commented on src/pages/RepoSearchPage/components/RepoBranchesDrawer/RepoBranchesDrawer.tsx
> +    const branches = () => {
Нет смысла усложнять код функциями. Либо выносить такие функции в отдельный компонент, либо прямо вставлять в Drawer. Необязательно ставить return, если единственное, что делает функция - это возвращает div. Например, в данном случае можно было сделать так:
`const branches = () => branchList?.map((branch: BranchItem): JSX.Element =>
         (
           <div className='repo-branches-drawer__item' key={branch.name}>
                  {branch.name}
           </div>
          );
     );`

2021-09-11 19:56 UTC, natalya-z commented on src/pages/RepoSearchPage/components/RepoBranchesDrawer/RepoBranchesDrawer.tsx
> +const RepoBranchesDrawer: React.FC<RepoBranchesDrawerProps> = ({
Так как в компоненте тоже происходит загрузка данных, следовало добавить `isLoading`, как в случае с компонентом `RepoSearchPage`

2021-09-11 20:04 UTC, natalya-z commented on src/pages/RepoSearchPage/components/RepoBranchesDrawer/RepoBranchesDrawer.tsx
> +const gitHubStore = new GitHubStore();
`GitHubStore` уже объявлен в компоненте `RepoSearchPage`. Не нужно объявлять его повторно, ведь тогда стор в этом компоненте и в `RepoSearchPage` будут разные. 
Функцию `getReposBranchesList` нужно вынести в функцию `onClickRepo` в `RepoSearchPage`. Тогда не будет необходимости прокидывать проп `selectedRepo`.  Так же вынести `branchList` в `RepoSearchPage` и прокидывать его как проп. Таким образом компонент `RepoBranchesDrawer` получится максимально тупым,   нужным только для отрисовки контент и не хранящим никакой логики.

2021-09-11 20:06 UTC, natalya-z commented on tsconfig.paths.json
> +      "@utils/*": ["src/utils/*"]
Здесь для удобства можно добавить store и share, зачем добавлять  utils и config, если таких папок нет

2021-09-11 20:09 UTC, natalya-z commented on src/components/ReposListContainer/ReposListContainer.tsx
> +const ReposListContainer = () => {
Компонент нигде не используется, зачем он?

2021-09-11 20:17 UTC, natalya-z commented on src/pages/RepoSearchPage/components/RepoBranchesDrawer/RepoBranchesDrawer.tsx
> +const gitHubStore = new GitHubStore();
`GitHubStore` уже объявлен в компоненте `RepoSearchPage`. Не нужно объявлять его повторно, ведь тогда сторы в этом компоненте и в `RepoSearchPage` будут разные.
Функцию `getReposBranchesList` нужно прокинуть из `RepoSearchPage` из уже существующего `gitHubStore`.

2021-09-11 20:25 UTC, natalya-z requested changes
ДЗ принято. 
Из критичных комментов обязательно поправь про переменную RepoItem и лишнее объявление стора GitHubStore в доп задания.

2021-09-12 16:01 UTC, Slava-Romanov commented
Внес изменения согласно замечаниям

2021-09-26 13:57 UTC, merged